### ISSUE TITLE
Failed to move page from housedetail to roomdetail

### ISSUE THREAD

**Issue by tuannghia0982** [BaoLTT/Room-Finding-System#283]
When clicking on the details of the hotel, there is a link error, written by the name of the hotel.

**Comment by BinhNHHE153478** [comment]
fix done.
![Uploading Ảnh chụp Màn hình 2023-12-09 lúc 19.00.54.png…]()

**Comment by BinhNHHE153478** [comment]
![Uploading Ảnh chụp Màn hình 2023-12-09 lúc 19.01.01.png…]()
